### ISSUE TITLE
Rename context numpy namespace variable

### ISSUE THREAD

**Issue by MTCam** [ecisneros8/pyrometheus#11]
I maintain that `actx_np` is not acceptable as a name. It suggests that the only thing this is usable for is meshmode's array context. That's not true. Instead, we need to describe what it is used for, and what is expected of it. The documentation you provide below begins to define that interface.

_Originally posted by @inducer in https://github.com/ecisneros8/pyrometheus/pull/7#discussion_r546098763_

**Comment by inducer** [comment]
@MTCam We're on `usr_np` now, so I think this is good to close.
