### ISSUE TITLE
Normalized vs. non-normalized Mass/Mole Fractions

### ISSUE THREAD

**Issue by cmikida2** [ecisneros8/pyrometheus#15]
In Cantera, the default when setting mass fractions includes "normalization," which among other things ensures that no negative mass fractions are present in the mixture. Code [here.](https://github.com/Cantera/cantera/blob/main/src/thermo/Phase.cpp#L420)

Another route, which is typically good for calculating Jacobians, is the not enforce that normalization, and allow for negative mass fractions, see code [here.](https://github.com/Cantera/cantera/blob/main/src/thermo/Phase.cpp#L434)

In Pyrometheus, there is no normalization/clipping of mass fractions at zero by default, nor is there an option for this. Given that it's the default setting for Cantera, and given the problems negative mass fractions can occasionally cause (I encountered this issue when trying to drive this example with explicit adaptive integration), should this exist a a user-exposed option when mass fractions are input to calculate concentrations, production rates, etc.?

The "pro" of doing this is that it would allow Pyrometheus to more directly replicate Cantera's typical operating condition, while one "con" is that it may be beyond the scope of what Pyrometheus is trying to accomplish/what sorts of applications it's targeted for. As a relative outsider, I'm mostly making this issue as a potential seed for discussion.

**Comment by MTCam** [comment]
I think Pyro deals with that here:
```python
    def get_concentrations(self, rho, mass_fractions):
        concs = self.iwts * rho * mass_fractions
        zero = _pyro_zeros_like(concs[0])
        for i, conc in enumerate(concs):
            concs[i] = self.usr_np.where(concs[i] > 0, concs[i], zero)
        return concs
```

**Comment by cmikida2** [comment]
Ahh - in that case it looks like I'm just the dummy that was using the wrong branch (kinetics).

**Comment by MTCam** [comment]
Actually I didn't realize it was much different in any other branch.  I just grabbed the one from the branch I/mirgecom uses.
