### ISSUE TITLE
Need interface to get mixture averaged thermo properties (e.g. Cp, Cv, Rs, gamma, h)

### ISSUE THREAD

**Issue by MTCam** [ecisneros8/pyrometheus#16]
Can `pyrometheus` provide an interface to ~~calculate~~ *return* mixture averaged thermo properties?  We could use these in our EOS and init utilities.  We can write them into the EOS, but it would be better (imo) if we can grab them from Pyro.

Context: https://github.com/illinois-ceesd/mirgecom/pull/236

**Comment by ecisneros8** [comment]
I agree pyro should do it. Do you want a generic interface e.g.,

def get_mixture_property(var)

or a host of targeted ones? If you want the first one, your branch already has this: 

https://github.com/ecisneros8/pyrometheus/blob/09f625ccf2005111522c781f206ba5c7d108fc9c/pyrometheus/__init__.py#L484

Also, do you want mole- or mass-averaging? 

[Pardon my poor github skills. I do not know how to paste links in a non-digusting way.]

**Comment by MTCam** [comment]
That's a really good point.  I could just use that generic function to calculate these. Let me think on that a minute :)

**Comment by MTCam** [comment]
Just want to bounce this off you @ecisneros8:

Pyro offers built-in interfaces to grab Cp_mix, and R_s.  I believe I can use these to get what I need at the moment these:

gamma_mix = Cp_mix / (Cp_mix - R_s)
c^2 = (gamma_mix * p) / rho

This seem ok to you?

**Comment by MTCam** [comment]
Closing this after a quick chat with Esteban on Slack.  Thanks @ecisneros8!

**Comment by inducer** [comment]
@MTCam Out of curiosity: what was the conclusion here?

**Comment by ecisneros8** [comment]
These formulae look good. I told @MTCam to make sure his mixture-averaged properties are consistent in their units.
