### ISSUE TITLE
messing up AD Jacobians computed using JAX.

### ISSUE THREAD

**Issue by MTCam** [ecisneros8/pyrometheus#22]
I found (... that np.where ...) is messing up Jacobians computed using JAX. All Jacobian entries associated with species with zero concentration come back zero, even when they shouldn't be. 

(Note, even when a mass fraction is zero, its corresponding Jacobian entries can be non-zero). I got rid of it, and I was able to verify the Jacobian of get_net_production_rates against finite differences and analytical expressions.

I'd much prefer these sorts of squashing to be done outside of pyro, and this is one example of why it's not best practice. Hope this is clear. Let me know otherwise.

_Originally posted by @ecisneros8 in https://github.com/ecisneros8/pyrometheus/pull/7#discussion_r603462914_

**Comment by inducer** [comment]
@MTCam Is this issue diferent from #21? (I'm not sure it is, but maybe there's something I'm missing.)
