### ISSUE TITLE
Need test case(s) for mirgecom

### ISSUE THREAD

**Issue by MTCam** [ecisneros8/pyrometheus#3]
There's an initial port of the prometheus methods to mirgecom [here](https://github.com/illinois-ceesd/mirgecom/pull/147/files#diff-fc0fa5db9cbc1ee49aadb12365e98ee998051498b28c31d5ee2b14b0257501ab).  

I do not mean to say this is the approach that should be taken for Prometheus in Mirgecom - but it is what I ended up doing to make it work.  I needed to use array context and discretization objects *inside* the mechanism code.   If we can integrate that into the (maybe mirgecom-specific) code generator, then great!  

Regardless, the mirgecom-facing `get_pressure` interface is working - and I need an initialization and test case just to check that I am getting the right pressures.   There are two tests I can think of:
- Set Y[1] = 1, Y[2-N] = 0, and check against known nitrogen gas configurations
- Set contrived mixture, and co-verify against Cantera

Are either of these testing configurations or mechanisms ready to go for re-use?

**Comment by ecisneros8** [comment]
Hi Mike,

1. We can integrate these changes into the code generator though, going forward, I'd like to have something more general. I'm curious as to what a discretization object does. Spatial derivatives? If so, I'd certainly try to avoid those inside pyrometheus (Prometheus?), as chemistry is local and should be implemented as such. 

2. I suggest co-verifying against Cantera as the best approach. Here's one example for pyrometheus (Prometheus?) get_pressure in the new code:

[](https://github.com/inducer/pyrometheus/blob/0b68105dc06a2d135381fabcc900dfb41483a6e4/test/test_codegen.py#L32)

It tests against the equilibrium composition (at constant density and internal energy). You can change the equivalence ratio (phi, line 43) to pick up mixtures with more radicals and reactants. At some point, it'd be useful to compile a database of ignition states (which have the most radicals) for tests like these.

**Comment by MTCam** [comment]
> Hi Mike,
> 
> 1. We can integrate these changes into the code generator though, going forward, I'd like to have something more general. I'm curious as to what a discretization object does. Spatial derivatives? If so, I'd certainly try to avoid those inside pyrometheus (Prometheus?), as chemistry is local and should be implemented as such.

At this point the array context and discretization are needed to be able to deal with the datastructures that are handed to the Prometheus interface. 

If pyrometheus code generators are meant to live outside mirgecom, and pyrometheus is intended to be a stand-alone library, then the discretization and array context stuff should not be sucked into the code generator.   On the other hand, if the code generator we are developing in this effort is a mirgecom-specific wrapper on prometheus, then it could easily pull in the discretization and array context. 

> 2. I suggest co-verifying against Cantera as the best approach. Here's one example for pyrometheus (Prometheus?) get_pressure in the new code [https://github.com/inducer/pyrometheus/blob/0b68105dc06a2d135381fabcc900dfb41483a6e4/test/test_codegen.py#L32](here). It tests against the equilibrium composition (at constant density and internal energy). You can change the equivalence ratio (phi, line 43) to pick up mixtures with more radicals and reactants. At some point, it'd be useful to compile a database of ignition states (which have the most radicals) for tests like these.

The question is, should we load and use Cantera inside mirgecom to implement this test, or should these Cantera-based co-verification tests be done as a part of pyrometheus intrinsic testing.   Given that the user can bring their own XML file and the end-game is that the mechanism will be generated on-the-fly, then it should be up to the code generator to generate the tests to go along with a given mechanism, right? (@inducer?).

**Comment by ecisneros8** [comment]
1. I'd like for pyrometheus to live outside of mirgecom to maximize its impact. There is a lot of interest in this sort of tool from combustion groups at LBNL and Sandia. Thinking beyond the review, we could have a mirgecom-specific fork, or a mirgecom interface (you'll tell me how these are bad ideas!).  

2. Cantera-based co-verification already is in place for the new generator. I thought you wanted to test *your* implementation. I don't know that every mechanism that is ever generated needs to be tested. Rather, we can test representative mechanisms that have common rate+thermo models (e.g., San Diego, GRI-3.2, UConn-32, ...).

**Comment by MTCam** [comment]
> 2. Cantera-based co-verification already is in place for the new generator. I thought you wanted to test _your_ implementation. I don't know that every mechanism that is ever generated needs to be tested. Rather, we can test representative mechanisms that have common rate+thermo models (e.g., San Diego, GRI-3.2, UConn-32, ...).

What I currently want is a test case that I can use right away to test the UIUC mechanism inside mirgecom.

**Comment by inducer** [comment]
> I'm curious as to what a discretization object does. Spatial derivatives? If so, I'd certainly try to avoid those inside pyrometheus (Prometheus?), as chemistry is local and should be implemented as such.

I agree with @ecisneros8 here. I'm not sure why a discretization object would be needed. Can you explain?

> I'd like for pyrometheus to live outside of mirgecom to maximize its impact.

I would be supportive of trying to make this a general tool that can *also* serve mirgecom. In my experience, that's almost always a healthy pressure.

FWIW, I also don't think this needs to/should become super dependent on the array context. It suffices if we can pass in a "numpy-like" module/namespace that we would like to be used, which doesn't harm external usability. (as one can simply pass in `numpy` itself, or we can pass in whatever the array context supplies)

> The question is, should we load and use Cantera inside mirgecom to implement this test, or should these Cantera-based co-verification tests be done as a part of pyrometheus intrinsic testing.

For now, my vote would be to shoot for assuming that Cantera is available at mirgecom runtime. IMO, that would be the easiest. The only wrinkle I can think of is a Power9 build. I suspect the easiest way out of this would be to start maintaining a conda-forge package for Cantera, probably building on https://github.com/Cantera/conda-recipes.

**Comment by MTCam** [comment]
> > I'm curious as to what a discretization object does. Spatial derivatives? If so, I'd certainly try to avoid those inside pyrometheus (Prometheus?), as chemistry is local and should be implemented as such.
> 
> I agree with @ecisneros8 here. I'm not sure why a discretization object would be needed. Can you explain?
> 

The one and only reason I added the discretization is so I could call the `norm` function and get something reasonable.   After struggling for quite a long time trying to figure out how to use the DOFArray on the inside of Prometheus without the array context or discretization to get a norm here:
```py
        for iter in range(num_iter):
            F = H_or_E - he_fun(T_i, Y)
            J = -pv_fun(T_i, Y)
            dT = -F / J
            T_i = T_i + dT
            tresid = actx.np.abs(dT)
            maxerr = self.discr.norm(tresid, np.inf)
            if maxerr < tol:
                break
```
I punted, and added access to the discretization.

> 
> FWIW, I also don't think this needs to/should become super dependent on the array context. It suffices if we can pass in a "numpy-like" module/namespace that we would like to be used, which doesn't harm external usability. (as one can simply pass in `numpy` itself, or we can pass in whatever the array context supplies)

This sounds great to me, but I'll need help figuring this out, or an example of what it looks like.  I've been struggling  hard with DOFArray juggling.

**Comment by MTCam** [comment]
Like this?

```py
def myfunc(self, mathcontext, other_args):
   ...
   mathcontext.where(stuff)
   mathcontext.abs(stuff2)
   ...
```
If so, any clues on how to get the convergence check?  `maxxerr = max(abs(dT))` does not seem to work.

**Comment by inducer** [comment]
https://github.com/inducer/meshmode/pull/85 makes `actx.np.linalg.norm` available. This also works on `DOFArrays`.

But now that I've written that, I'm once again confused by the need for it. Where do these tests live? If they live in mirgecom, they're allowed to know about the array context. If they live in pyrometheus, they are not (but then they're probably numpy arrays, and none of this is an issue).

**Comment by MTCam** [comment]
> [inducer/meshmode#85](https://github.com/inducer/meshmode/pull/85) makes `actx.np.linalg.norm` available. This also works on `DOFArrays`.
> 
> But now that I've written that, I'm once again confused by the need for it. Where do these tests live? If they live in mirgecom, they're allowed to know about the array context. If they live in pyrometheus, they are not (but then they're probably numpy arrays, and none of this is an issue).

**Comment by MTCam** [comment]
All thumbs.

**Comment by inducer** [comment]
For completeness: https://github.com/illinois-ceesd/mirgecom/pull/147#discussion_r526947163 points to where the norm is needed. @MTCam and I resolved in our conversation that the numpy module (or fake numpy module from the array context) to be used by the `Thermochemistry` class would be passed into the constructor. @ecisneros8, does that sound reasonable to you?

**Comment by MTCam** [comment]
There are a few issues.   Currently, I need to `import numpy as realnp` to get at `realnp.array`, `realnp.abs`, `realnp.inf`.   Next, the norm function gives the following error:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../mirgecom/eos.py:305: in pressure
    temperature = self.temperature(cv)
../mirgecom/eos.py:338: in temperature
    return self._prometheus_mech.get_temperature(e, tguess, y, True)
../mirgecom/prometheus.py:515: in get_temperature
    maxerr = self.np.linalg.norm(tresid, realnp.inf)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <meshmode.array_context._PyOpenCLFakeNumpyLinalgNamespace object at 0x7f5d803a0940>
array = array([[[array(1674.97143311), array(1674.97151309)]]], dtype=object), ord = inf

    def norm(self, array, ord=None):
        if len(array.shape) != 1:
>           raise NotImplementedError("only vector norms are implemented")
E           NotImplementedError: only vector norms are implemented

../../meshmode/meshmode/array_context.py:353: NotImplementedError
----------------------------------------------- Captured stdout call -----------------------------------------------
```

**Comment by inducer** [comment]
That means you're giving it a 2 (or higher) D array. (I don't know why.) Are you manually unpacking a `DOFArray`?

**Comment by ecisneros8** [comment]
@MTCam filled me in on the norm issue, and using numpy versus the array-context version. I find it reasonable, and can incorporate these changes to the code generator once I finish the kinetics backbone (almost done).

**Comment by MTCam** [comment]
> That means you're giving it a 2 (or higher) D array. (I don't know why.) Are you manually unpacking a `DOFArray`?

Extraneous call to np.abs removed.  Let's see if that clears it up.  
```
dt = DOFArray((array([[1674.97143311, 1674.97151309]]),))
np.abs(dt) = array([[[array(1674.97143311), array(1674.97151309)]]], dtype=object)
```

**Comment by MTCam** [comment]
Here are the tests I am currently using:

Ramping input condition (p,T)=(1atm, 300K) --> (20atm, 6000K), for N2-only *and* a mixture Y= <.1, .01, .001, ..> for each species, with Y_N2 = 1.0 - sum(Y_reactants)

- check that _Pyrometheus_ and _Cantera_ get the same T, e (relative error within 1e-6) 
- check that PyrometheusMixtureEOS and _Pyrometheus_ get the same answers for T, e, and p.   

In the EOS test, PyrometheusMixtureEOS uses Tguess = 300.0, but the mixture soln is initialized using the proper p,T,e given by Cantera.

Needed:
Tests for chemical mechanism

**Comment by ecisneros8** [comment]
My understanding is that we have a solid set of tests for mirgecom-oriented pyro. Can we vote to close this issue @MTCam, @inducer?

**Comment by MTCam** [comment]
The native tests are reproduced in the MIRGE-Com tests with additional ones that test the use within the Euler solver in this [PR](https://github.com/illinois-ceesd/mirgecom/pull/147) .
