### ISSUE TITLE
Set up RTD

### ISSUE THREAD

**Issue by inducer** [ecisneros8/pyrometheus#9]
@ecisneros8 To finish RTD setup, you need to

- [x] Add https://readthedocs.org/api/v2/webhook/pyrometheus/141765/ as a webhook at https://github.com/ecisneros8/pyrometheus/settings/hooks/new
- [x] Send me your user name on https://readthedocs.org/ so that I can add you to the project.

**Comment by inducer** [comment]
Btw docs are live: https://pyrometheus.readthedocs.io/en/latest/ but won't update automatically until the first step above is completed.

**Comment by ecisneros8** [comment]
My user readthedocs username is ecisneros8. I think I added the hook correctly.

**Comment by inducer** [comment]
Added you, you should see that on your end.

> I think I added the hook correctly.

Cool. We'll see if the docs update on the next change. If not, we'll troubleshoot then.

**Comment by inducer** [comment]
Looks like it worked:

![image](https://user-images.githubusercontent.com/352067/102552459-e2374380-4086-11eb-9b1b-97433a8a241d.png)
